export function downloadAsTXT(content: string, filename: string) {
  const blob = new Blob([content], { type: "text/plain" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${filename}.txt`;
  a.click();
  URL.revokeObjectURL(url);
}

export function downloadAsHTML(content: string, filename: string, productName: string) {
  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>${filename}</title>
  <style>
    body { font-family: Georgia, serif; max-width: 800px; margin: 40px auto; padding: 20px; color: #1a1a1a; line-height: 1.8; }
    .header { background: #7c3aed; color: white; padding: 20px; border-radius: 10px; margin-bottom: 30px; }
    pre { white-space: pre-wrap; font-family: Georgia, serif; }
    .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #e5e7eb; color: #9ca3af; font-size: 12px; text-align: center; }
  </style>
</head>
<body>
  <div class="header">
    <h1>${filename}</h1>
    <p>Generated for ${productName} · ${new Date().toLocaleDateString()}</p>
  </div>
  <pre>${content}</pre>
  <div class="footer">Generated by AI Marketing Co-Pilot</div>
</body>
</html>`;
  const blob = new Blob([html], { type: "text/html" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${filename}.html`;
  a.click();
  URL.revokeObjectURL(url);
}

export function printAsPDF(content: string, filename: string, productName: string) {
  const printWindow = window.open("", "_blank");
  if (!printWindow) return;
  printWindow.document.write(`<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>${filename}</title>
  <style>
    body { font-family: Georgia, serif; max-width: 800px; margin: 40px auto; padding: 20px; color: #1a1a1a; line-height: 1.8; }
    .header { background: #7c3aed; color: white; padding: 20px; border-radius: 10px; margin-bottom: 30px; }
    pre { white-space: pre-wrap; font-family: Georgia, serif; }
    @media print { body { margin: 0; } }
  </style>
</head>
<body>
  <div class="header">
    <h1>${filename}</h1>
    <p>Generated for ${productName} · ${new Date().toLocaleDateString()}</p>
  </div>
  <pre>${content}</pre>
</body>
</html>`);
  printWindow.document.close();
  setTimeout(() => { printWindow.print(); printWindow.close(); }, 500);
}
